
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      -  ./src/data/3mo-prices.ndjson:/app/data/3mo-prices.ndjson # to include price file
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/profit/minmax"]
      interval: 30s
      timeout: 10s
      retries: 3

  # frontend:
  #   build:
  #     context: ./stock-profit-frontend
  #   env_file:
  #     - ./stock-profit-frontend/.env
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
