
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      -  ./src/data/3mo-prices.ndjson:/app/dist/data/3mo-prices.ndjson:ro # mount into dist/data for runtime
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # frontend:
  #   build:
  #     context: ./stock-profit-frontend
  #   env_file:
  #     - ./stock-profit-frontend/.env
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
