# Use official Node image to build Vue app
FROM node:18 AS frontend-build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Use nginx to serve
FROM nginx:alpine
COPY --from=frontend-build /app/dist /usr/share/nginx/html
EXPOSE 80
