# GitHub Actions workflow for deploying to Azure Web App (Linux F1)
name: Build and deploy Node.js + Vue app to Azure (Linux)

on:
  push:
    branches:
      - master       # adjust if your default branch is 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'   # match your Linux runtime

      - name: Install & build backend
        working-directory: .
        run: |
          npm install
          npm run build

      - name: Install & build frontend
        working-directory: ./stock-profit-frontend
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
        run: |
          npm install
          npm run build
          if [ -z "${VITE_API_KEY}" ]; then
            echo "❌ VITE_API_KEY empty"
            exit 1
          else
            echo "✅ VITE_API_KEY present"
          fi

      - name: Debug public folder
        run: |
          echo "—— Contents of project-root/public ——"
          ls -R public

      - name: Package production artifacts
        run: |
          zip -r release.zip \
            package.json package-lock.json \
            public \
            stock-profit-frontend/dist \
            -x "**/node_modules/**"

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-package
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: release-package
          path: .

      - name: Deploy to Azure Web App (Linux)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stock-profit-app' 
          slot-name: 'Production'
          package: 'release.zip'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
